In [2]:
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

import xesmf

In [9]:
ds2 = xesmf.util.grid_global(2, 2, cf=True, lon1=360)
ds3 = xesmf.util.grid_global(3, 3, cf=True, lon1=360)
ds4 = xesmf.util.grid_global(4, 4, cf=True, lon1=360)

In [10]:
ds2.lat

<xarray.DataArray 'lat' (lat: 90)> Size: 720B
array([-89., -87., -85., -83., -81., -79., -77., -75., -73., -71., -69., -67.,
       -65., -63., -61., -59., -57., -55., -53., -51., -49., -47., -45., -43.,
       -41., -39., -37., -35., -33., -31., -29., -27., -25., -23., -21., -19.,
       -17., -15., -13., -11.,  -9.,  -7.,  -5.,  -3.,  -1.,   1.,   3.,   5.,
         7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,  25.,  27.,  29.,
        31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,  49.,  51.,  53.,
        55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,  73.,  75.,  77.,
        79.,  81.,  83.,  85.,  87.,  89.])
Coordinates:
  * lat                 (lat) float64 720B -89.0 -87.0 -85.0 ... 85.0 87.0 89.0
    latitude_longitude  float64 8B nan
Attributes:
    bounds:         lat_bounds
    standard_name:  latitude
    units:          degrees_north

In [11]:
ds3.lat

<xarray.DataArray 'lat' (lat: 60)> Size: 480B
array([-88.5, -85.5, -82.5, -79.5, -76.5, -73.5, -70.5, -67.5, -64.5, -61.5,
       -58.5, -55.5, -52.5, -49.5, -46.5, -43.5, -40.5, -37.5, -34.5, -31.5,
       -28.5, -25.5, -22.5, -19.5, -16.5, -13.5, -10.5,  -7.5,  -4.5,  -1.5,
         1.5,   4.5,   7.5,  10.5,  13.5,  16.5,  19.5,  22.5,  25.5,  28.5,
        31.5,  34.5,  37.5,  40.5,  43.5,  46.5,  49.5,  52.5,  55.5,  58.5,
        61.5,  64.5,  67.5,  70.5,  73.5,  76.5,  79.5,  82.5,  85.5,  88.5])
Coordinates:
  * lat                 (lat) float64 480B -88.5 -85.5 -82.5 ... 82.5 85.5 88.5
    latitude_longitude  float64 8B nan
Attributes:
    bounds:         lat_bounds
    standard_name:  latitude
    units:          degrees_north

In [46]:
clat = np.concatenate(
    [
        np.arange(-89, -65, 2),
        np.arange(-65, -44, 3),
        np.arange(-44, 44, 4),
        np.arange(44, 65, 3),
        np.arange(65, 90, 2),
    ],
)

In [47]:
clat

array([-89, -87, -85, -83, -81, -79, -77, -75, -73, -71, -69, -67, -65,
       -62, -59, -56, -53, -50, -47, -44, -40, -36, -32, -28, -24, -20,
       -16, -12,  -8,  -4,   0,   4,   8,  12,  16,  20,  24,  28,  32,
        36,  40,  44,  47,  50,  53,  56,  59,  62,  65,  67,  69,  71,
        73,  75,  77,  79,  81,  83,  85,  87,  89])

In [48]:
cds = xr.Dataset()
cds["lon"] = ds4.lon
cds["lat"] = xr.DataArray(
    clat,
    coords={"clat": clat},
)

In [49]:
clon = ds4.lon.values

In [50]:
lon, lat = np.meshgrid(clon, clat)

In [53]:
np.savez("latent-graduatedx2-4.global1degree.npz", lon=lon, lat=lat)

In [54]:
cds.to_netcdf("latent-graduatedx2-4.global1degree.nc")